package com.bancosap.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    USER_BLOCKED_ADMIN,
    USER_UNBLOCKED_ADMIN,
    TRANSFER_EXECUTED,
    PIX_KEY_CREATED,
    PIX_KEY_DELETED,
    PIX_SENT,
    BILL_PAID,
    DEPOSIT_MADE,
    CARD_CREATED,
    CARD_STATUS_CHANGED,
    CARD_LIMIT_UPDATED,
    CARD_PURCHASE_SIMULATED,
    CRYPTO_BOUGHT,
    CRYPTO_SOLD,
    CRYPTO_TRANSFERRED,
    ADMIN_LIMIT_UPDATED
}
